// This file is part of mathtrader.
//
// Copyright (C) 2021 George Ioannidis
//
// mathtrader is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// mathtrader is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with mathtrader. If not, see <http://www.gnu.org/licenses/>.

// Utility functions for Nodes. These generate the Node ids that represent an
// offered or wanted item, respectively, given an item id.
//
// A given item maps to two Nodes, which we refer to as "offered" and "wanted"
// nodes. Their respective ids are generated by appending a '+' and '-' suffix,
// respectively, to the original item id.

#ifndef MATHTRADER_NETWORK_INTERNAL_NODE_UTIL_H_
#define MATHTRADER_NETWORK_INTERNAL_NODE_UTIL_H_

#include <string>

namespace mathtrader::network::internal {

// Generates the id of the offered Node, from the item id.
inline std::string GetOfferedNodeId(std::string item_id) {
  item_id.push_back('+');
  return item_id;
}

// Generates the id of the wanted Node, from the item id.
inline std::string GetWantedNodeId(std::string item_id) {
  item_id.push_back('-');
  return item_id;
}

}  // namespace mathtrader::network::internal

#endif  // MATHTRADER_NETWORK_INTERNAL_NODE_UTIL_H_
